### PR TITLE
Refactor ggvega TypeScript

### PR DESCRIPTION
**Pull request by wenyuyangpku**
still on working

### CODE REVIEW

**Comment by ijlyttle** [comment]
This PR will fix #33

**Comment by ijlyttle** [comment]
@haleyjeppson - my thought is to merge this, perhaps very soon, because it would give us a chance to propose updates to ggschema as a part of #40. To be sure, there is still work to be done on the ggvega refactoring, this work would continue in this branch and in a new PR.

@wenyuyangpku - just to be sure that in the refactoring in #40, as it is now, the scatterplot still works. 

I am about to make a first PR on testing that can help us be sure that any changes we make do not break things at a very-high level.

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle ,

I am sure the scatterplot is still working. Here is the output:

```{r}
as_vegaspec(p)
#> Warning: ggSpec.layers[0] should NOT have additional properties
#> Warning: ggSpec.layers[0].geom_params should NOT have additional properties
#> Warning: ggSpec.layers[0].stat should NOT have additional properties
#> Warning: ggSpec.layers[0].stat should NOT have additional properties
```

**Comment by ijlyttle** [comment]
merging into master to get the ggschema changes (will use them in stat branch)

**Pull request merged**
