### PR TITLE
Get TS working again

### LINKED ISSUE #53: Get TS working again
Issue to solve for #52

### PR DESCRIPTION
**Pull request by ijlyttle**
This PR will fix #53.

Hi @wenyuyangpku, 

I did not see a PR from you yet, so I hope it would be OK for me to open this, then we could both contribute to get everything working again.

If I remember correctly, we would need from you either a polyfill/transpile fix for `Map`, or a reversion to using plain objects.

This should get all the tests passing again, then we can continue work to refactor the existing TS.

### CODE REVIEW

**Comment by ijlyttle** [comment]
On the ggschema side, I thought I would turn `GeomParams` into an `any`. The content of this will depend on the class of the `Geom`, so it may be difficult to generalize what will be in there.

@wenyuyangpku - this is not an urgent question, but could it be possible to specify the content of `GeomParams` according to the class of the `Geom`?

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle ,

Sorry about I cannot use  `polyfill/transpile` to fix it right now. I just remove all `Map` and It works for all our tests. 

About the `geom_params` and `geom` question, I can give you an example in next commit.

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle 

About the `.yarnrc`, should it be ignored?

**Comment by ijlyttle** [comment]
Yes - let me take care of that - I am using a global `~/.yarnrc` so I should delete the local one as well.

**Comment by ijlyttle** [comment]
I think there are a couple of items to resolve before merging:

- In `.travis.yml`, should be install and build ggschema before we install and build ggvega? Would this ensure that our tests are using the most-recent built ggschema?

https://github.com/vegawidget/ggvega/blob/889325cf193f7d401e3d53a63487f5ae1d9a2545/.travis.yml#L38-L41

If you think so, @wenyuyangpku, I will be happy to make the change.

- Look at `geom`/`geom_params` idea.

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle ，

I think we don't need to build ggschema.

When we build TypeScript ggvega, both ggvega and ggschema are compiled. This is because we import ggschema class into ggvega. But it doesn't generate a new `ggschema.json`. If we want to generate a new  `ggschema.json`, we have to run `yarn build` in the ggschema folder.

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle ,

Here is a solution for the `geom_params` and `geom` question.  I divide the `Layer` type to `BaseLayer` and `Geom`. Since `Geom` has both `geom` and `geom_params`, we can make sure different `geom` has different `geom_params`.

https://github.com/vegawidget/ggvega/blob/d20c0199f365f5efd090eed492fe96016a17d8e1/src-ext/TypeScript/ggschema/src/layer.ts#L9-L17

https://github.com/vegawidget/ggvega/blob/d20c0199f365f5efd090eed492fe96016a17d8e1/src-ext/TypeScript/ggschema/src/layerGeom.ts#L1-L11

**Comment by ijlyttle** [comment]
Hi @wenyuyangpku,

Thanks for the example on `geom`/`geom_param` - I have extended it to `stat`/`stat_param`.

Can you have a look to make sure that I did everything OK? One thing I have a question about is the field `na.rm` in `geom_param` or `stat_param`. My approach was to surround it in quotes:

https://github.com/vegawidget/ggvega/blob/b7e23be34fc2383050b65dfb9180aa023e67f25f/src-ext/TypeScript/ggschema/src/layerGeom.ts#L3-L8

Given your description, I think I will build ggschema in Travis, so that we can be sure that the tests reflect the current state of the code in ggschema.

**Comment by ijlyttle** [comment]
@wenyuyangpku: nice catch on the directory 👍

**Pull request merged**
