### PR TITLE
Switch to Vega-Lite classes

### LINKED ISSUE #76: Use Vega-Lite classes
The idea is to use the Vega-Lite classes directly, rather than using the quicktype classes.

This has become feasible because V8's engine is now fully ES6 compliant.

The first step is to switch over to VL classes using VL3. Once this is working, then we will switch from VL3 to VL4.

### PR DESCRIPTION
**Pull request by ijlyttle**
Fix #76

### CODE REVIEW

**Comment by ijlyttle** [comment]
Hi @wenyuyangpku - here's what I have so far - I have switched over to Vega-Lite classes and got most of the "red squiggly lines" to go away, but not all. 

It's possible I have done things very wrong, as well.

Whenever you might have some time, could you have a look and possibly offer some suggestions?

Thanks!

**Comment by ijlyttle** [comment]
Just to try to write out some of my thoughts and technical frustrations:

I want to get things working first for VL 3.3.0 (the version in effect this summer) - once that works and I have a good understanding of it (ha!), then I'd like to move to VL 4.0.x.

The two biggest questions I have so far:

1. I don't *really* understand what's going on with the angle brackets associated with the classes. My superficial understanding is that this is a way to pass through a type that is then enforced within a class, as a way to make things more generic.

   My way to deal with this is type whatever gets rid of the "red squiggly line". I don't think this is a strategy for long-term success. It may not even be a strategy for short-term success.

2. Are Vega-Lite and ajv dev dependencies or are they "real" dependencies? I ask this because we are calling their functions in our code.

**Comment by ijlyttle** [comment]
I've got the red-squiggly lines to go away in the source code.

Next - I need to update the tests.

**Comment by ijlyttle** [comment]
now having problems with `yarn build` - there seem to be a lot of errors building vega-lite...

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle , I think you have done a good job. 

The only problem is that you **import** all vega-lite code from folder `./node_modules/vega-lite/src/`. However, in ggvega, we only compile the code in folder `./src`. That means the code you imported from `./node_modules/vega-lite/src/` doesn't work. 

One of the solustion is to **import** all vega-lite code from folder `./node_modules/vega-lite/build/src/`. The code in `./build` folder are all compiled to Javascript. And the  `yarn build` works.

**Comment by ijlyttle** [comment]
Thanks, that did the trick! 

If you have any thoughts on the questions, I'd appreciate the opportunity to discuss. That being said, having code that compiles and passes makes things a lot easier :)

**Comment by ijlyttle** [comment]
All the lights are green!

**Comment by wenyuyangpku** [comment]
About the two questions, just my understanding...

1. I don't have any better idea. I also think it's a way to pass through a type. Generic type also has other functions. But I think we only need to care about the class/type part. Maybe you this article can help you. 
  [https://blog.bitsrc.io/understanding-generics-in-typescript-1c041dc37569](https://blog.bitsrc.io/understanding-generics-in-typescript-1c041dc37569)

2. Since we don't publish a npm pachkage, I think we don't need to care about the  `dev dependencies` or ` dependencies`. The functions in `dependencies` should be included in the `ggvega.js`.

**Comment by ijlyttle** [comment]
Thanks! I'll look through the reference you provided - I think I might understand this better as I (try to) use it more.

I'll have a look in ggvega.js for external code. I don't think we are considering publishing to npm, but I'd like to follow the practices anyway.

Thanks again!

**Pull request merged**
