### PR TITLE
update ggschema

### PR DESCRIPTION
**Pull request by wenyuyangpku**
cherry-pick `ggschema` from `refator-TS`

### CODE REVIEW

**Comment by wenyuyangpku** [comment]
I have done some changes. I renamed `gsSpec.ts` to `toplevel.ts`  and added a new file `index.ts` to export all class in ggschema. Another change is that I rewrited the `ScaleType`. Now `ScaleType` only has `log`.

**Comment by ijlyttle** [comment]
Hi again @wenyuyangpku,

I have proposed some changes here. Having separate files for the geom and stat definitions will make it easier for me to propose extensions.

One question I have is about the current definition of `Stat`. If we update the definition of `Stat` in the next few days, would it cause the tests to fail? We can discuss at our next meeting.

If you think these changes are OK, please merge them back into `refactor-TS`. Happy to discuss whenever.

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle ,

Sorry to reply to you so late. I agree with your changes and I added the import statements.

About the Stat, I think you can add it. Because we don't have `stat` function and test, and `avj` only throws warnings, the check should pass.

I have merged it to `refactor-TS` and it passed the checks.

**Comment by ijlyttle** [comment]
Thanks, @wenyuyangpku!

Closing because this was merged into `refactor-TS`

**Pull request closed without merging**
